// 생성물 — .claude/gen_cage_cases.py 가 만든다. 손으로 고치지 말 것.
const CAGE_CASES = [
 {
  "name": "HD현대 (HD Hyundai)",
  "year": "1972",
  "country": "🇰🇷",
  "unit": "atom",
  "outcome": "성공",
  "cage": "🔭",
  "ch": 2,
  "room": "상상",
  "loop": "L",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "LS일렉트릭 (LS Electric)",
  "year": "1974",
  "country": "🇰🇷",
  "unit": "second",
  "outcome": "성공",
  "cage": "🔭",
  "ch": 2,
  "room": "상상",
  "loop": "L",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "SK바이오팜 (SK Biopharmaceuticals)",
  "year": "1993",
  "country": "🇰🇷",
  "unit": "cell",
  "outcome": "성공",
  "cage": "💒",
  "ch": 3,
  "room": "설득",
  "loop": "L",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "Aduhelm (Biogen)",
  "year": "2021",
  "country": "🇺🇸",
  "unit": "cell",
  "outcome": "실패(승인 논란)",
  "cage": "🌷",
  "ch": 7,
  "room": "지식",
  "loop": "R",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "Airbnb",
  "year": "2008",
  "country": "🇺🇸",
  "unit": "bit",
  "outcome": "성공",
  "cage": "🔭",
  "ch": 2,
  "room": "상상",
  "loop": "L",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "ASML",
  "year": "1984",
  "country": "🇳🇱",
  "unit": "atom",
  "outcome": "성공",
  "cage": "🌷",
  "ch": 7,
  "room": "지식",
  "loop": "R",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "Better Place",
  "year": "2007",
  "country": "🇮🇱",
  "unit": "second",
  "outcome": "실패",
  "cage": "🌷",
  "ch": 7,
  "room": "지식",
  "loop": "R",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "Beyond Meat",
  "year": "2009",
  "country": "🇺🇸",
  "unit": "cell",
  "outcome": "실패(붕괴)",
  "cage": "🌫️",
  "ch": 8,
  "room": "손익",
  "loop": "R",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "Ferrari",
  "year": "1947",
  "country": "🇮🇹",
  "unit": "atom",
  "outcome": "성공",
  "cage": "⏱️",
  "ch": 4,
  "room": "폭파",
  "loop": "L",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "Flagship Pioneering",
  "year": "2000",
  "country": "🇺🇸",
  "unit": "cell",
  "outcome": "성공",
  "cage": "💒",
  "ch": 3,
  "room": "설득",
  "loop": "L",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "Gowex",
  "year": "",
  "country": "🇪🇸",
  "unit": "bit",
  "outcome": "실패(분식회계)",
  "cage": "🌫️",
  "ch": 8,
  "room": "손익",
  "loop": "R",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "Groq",
  "year": "2016",
  "country": "🇺🇸",
  "unit": "atom",
  "outcome": "성공",
  "cage": "🐦‍⬛",
  "ch": 9,
  "room": "기준",
  "loop": "R",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "Honda",
  "year": "1948",
  "country": "🇯🇵",
  "unit": "atom",
  "outcome": "성공",
  "cage": "🔭",
  "ch": 2,
  "room": "상상",
  "loop": "L",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "Impossible Foods",
  "year": "2011",
  "country": "🇺🇸",
  "unit": "cell",
  "outcome": "성공",
  "cage": "🌫️",
  "ch": 8,
  "room": "손익",
  "loop": "R",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "Intel",
  "year": "1968",
  "country": "🇺🇸",
  "unit": "atom",
  "outcome": "위기 중",
  "cage": "💒",
  "ch": 3,
  "room": "설득",
  "loop": "L",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "Juicero",
  "year": "2013",
  "country": "🇺🇸",
  "unit": "atom",
  "outcome": "실패",
  "cage": "🪞",
  "ch": 1,
  "room": "욕망",
  "loop": "L",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "LeEco",
  "year": "2004",
  "country": "🇨🇳",
  "unit": "bit",
  "outcome": "실패(과확장·자금경색)",
  "cage": "🦋",
  "ch": 6,
  "room": "고통",
  "loop": "R",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "Lytro",
  "year": "2006",
  "country": "🇺🇸",
  "unit": "atom",
  "outcome": "실패",
  "cage": "🪞",
  "ch": 1,
  "room": "욕망",
  "loop": "L",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "Magic Leap",
  "year": "2010",
  "country": "🇺🇸",
  "unit": "atom",
  "outcome": "피봇",
  "cage": "🪞",
  "ch": 1,
  "room": "욕망",
  "loop": "L",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "MercadoLibre",
  "year": "1999",
  "country": "🇦🇷",
  "unit": "bit",
  "outcome": "성공",
  "cage": "🌫️",
  "ch": 8,
  "room": "손익",
  "loop": "R",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "Novo Nordisk",
  "year": "1923",
  "country": "🇩🇰",
  "unit": "cell",
  "outcome": "성공",
  "cage": "🌷",
  "ch": 7,
  "room": "지식",
  "loop": "R",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "Nubank",
  "year": "2013",
  "country": "🇧🇷",
  "unit": "bit",
  "outcome": "성공",
  "cage": "🌫️",
  "ch": 8,
  "room": "손익",
  "loop": "R",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "Pivot Bio",
  "year": "2011",
  "country": "🇺🇸",
  "unit": "cell",
  "outcome": "성공",
  "cage": "🌫️",
  "ch": 8,
  "room": "손익",
  "loop": "R",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "Quibi",
  "year": "2018",
  "country": "🇺🇸",
  "unit": "bit",
  "outcome": "실패",
  "cage": "🪞",
  "ch": 1,
  "room": "욕망",
  "loop": "L",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "Theranos",
  "year": "2003",
  "country": "🇺🇸",
  "unit": "cell",
  "outcome": "실패",
  "cage": "💒",
  "ch": 3,
  "room": "설득",
  "loop": "L",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "달바 (d'Alba)",
  "year": "2018",
  "country": "🇰🇷",
  "unit": "bit",
  "outcome": "성장 중",
  "cage": "🪞",
  "ch": 1,
  "room": "욕망",
  "loop": "L",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "두산",
  "year": "1896",
  "country": "🇰🇷",
  "unit": "second",
  "outcome": "성공",
  "cage": "⏱️",
  "ch": 4,
  "room": "폭파",
  "loop": "L",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "뤼튼 (Wrtn)",
  "year": "2021",
  "country": "🇰🇷",
  "unit": "bit",
  "outcome": "성장 중",
  "cage": "⏱️",
  "ch": 4,
  "room": "폭파",
  "loop": "L",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "리피드 (Lipid)",
  "year": "2020",
  "country": "🇰🇷",
  "unit": "atom",
  "outcome": "초기 성장",
  "cage": "🔭",
  "ch": 2,
  "room": "상상",
  "loop": "L",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "무신사 (Musinsa)",
  "year": "2001",
  "country": "🇰🇷",
  "unit": "bit",
  "outcome": "성장 중",
  "cage": "🪞",
  "ch": 1,
  "room": "욕망",
  "loop": "L",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "배달의민족",
  "year": "2010",
  "country": "🇰🇷",
  "unit": "bit",
  "outcome": "인수(성공)",
  "cage": "🐦‍⬛",
  "ch": 9,
  "room": "기준",
  "loop": "R",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "삼성바이오로직스 (Samsung Biologics)",
  "year": "2011",
  "country": "🇰🇷",
  "unit": "cell",
  "outcome": "성공",
  "cage": "💒",
  "ch": 3,
  "room": "설득",
  "loop": "L",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "셀트리온 (Celltrion)",
  "year": "2002",
  "country": "🇰🇷",
  "unit": "cell",
  "outcome": "성공",
  "cage": "💒",
  "ch": 3,
  "room": "설득",
  "loop": "L",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "알테오젠 (Alteogen)",
  "year": "2008",
  "country": "🇰🇷",
  "unit": "cell",
  "outcome": "성장 중",
  "cage": "💒",
  "ch": 3,
  "room": "설득",
  "loop": "L",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "야놀자 (Yanolja)",
  "year": "2005",
  "country": "🇰🇷",
  "unit": "bit",
  "outcome": "성장 중",
  "cage": "🪞",
  "ch": 1,
  "room": "욕망",
  "loop": "L",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "에이비엘바이오 (ABL Bio)",
  "year": "2016",
  "country": "🇰🇷",
  "unit": "cell",
  "outcome": "성장 중",
  "cage": "💒",
  "ch": 3,
  "room": "설득",
  "loop": "L",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "카카오 (Kakao)",
  "year": "2010",
  "country": "🇰🇷",
  "unit": "bit",
  "outcome": "위기 중",
  "cage": "🐦‍⬛",
  "ch": 9,
  "room": "기준",
  "loop": "R",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "컬리 (Kurly)",
  "year": "2015",
  "country": "🇰🇷",
  "unit": "bit",
  "outcome": "성장 중",
  "cage": "🪞",
  "ch": 1,
  "room": "욕망",
  "loop": "L",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "쿠팡 (Coupang)",
  "year": "2010",
  "country": "🇰🇷",
  "unit": "bit",
  "outcome": "성장 중",
  "cage": "⏱️",
  "ch": 4,
  "room": "폭파",
  "loop": "L",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "크래프톤 (Krafton)",
  "year": "2007",
  "country": "🇰🇷",
  "unit": "bit",
  "outcome": "성공",
  "cage": "⏱️",
  "ch": 4,
  "room": "폭파",
  "loop": "L",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "토스 (Toss/Viva Republica)",
  "year": "2013",
  "country": "🇰🇷",
  "unit": "bit",
  "outcome": "성장 중",
  "cage": "🐦‍⬛",
  "ch": 9,
  "room": "기준",
  "loop": "R",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "한화에어로스페이스 (Hanwha Aerospace)",
  "year": "1977",
  "country": "🇰🇷",
  "unit": "atom",
  "outcome": "성공",
  "cage": "🔭",
  "ch": 2,
  "room": "상상",
  "loop": "L",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "한화오션 (Hanwha Ocean)",
  "year": "1973",
  "country": "🇰🇷",
  "unit": "atom",
  "outcome": "성공",
  "cage": "🔭",
  "ch": 2,
  "room": "상상",
  "loop": "L",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "닌텐도 (Nintendo)",
  "year": "1889",
  "country": "🇯🇵",
  "unit": "bit",
  "outcome": "성공",
  "cage": "🦋",
  "ch": 6,
  "room": "고통",
  "loop": "R",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "텐센트 (Tencent)",
  "year": "1998",
  "country": "🇨🇳",
  "unit": "bit",
  "outcome": "성공",
  "cage": "🦋",
  "ch": 6,
  "room": "고통",
  "loop": "R",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "Moderna",
  "year": "2010",
  "country": "🇺🇸",
  "unit": "cell",
  "outcome": "성공",
  "cage": "💒",
  "ch": 3,
  "room": "설득",
  "loop": "L",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "Netafim",
  "year": "1965",
  "country": "🇮🇱",
  "unit": "atom",
  "outcome": "성공",
  "cage": "🌷",
  "ch": 7,
  "room": "지식",
  "loop": "R",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "라인 (LINE)",
  "year": "2011",
  "country": "🇯🇵",
  "unit": "bit",
  "outcome": "성공",
  "cage": "🦋",
  "ch": 6,
  "room": "고통",
  "loop": "R",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "Kodak",
  "year": "1892",
  "country": "🇺🇸",
  "unit": "bit",
  "outcome": "실패(파산)",
  "cage": "🔭",
  "ch": 2,
  "room": "상상",
  "loop": "L",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "Tesla",
  "year": "2003",
  "country": "🇺🇸",
  "unit": "atom",
  "outcome": "성공",
  "cage": "🌷",
  "ch": 7,
  "room": "지식",
  "loop": "R",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "Faraday Future",
  "year": "2014",
  "country": "🇺🇸",
  "unit": "atom",
  "outcome": "실패",
  "cage": "🦋",
  "ch": 6,
  "room": "고통",
  "loop": "R",
  "held": "",
  "src": "tolzul"
 },
 {
  "name": "Vestiaire Collective",
  "year": "2009",
  "country": "🌐",
  "unit": "",
  "outcome": "RETAIL/FASHION",
  "cage": "🪞",
  "ch": 1,
  "room": "욕망",
  "loop": "L",
  "held": "아동복이냐 중고명품이냐 — 둘 다 아직 없는 것",
  "src": "bocconi"
 },
 {
  "name": "Uber",
  "year": "2010",
  "country": "🌐",
  "unit": "",
  "outcome": "TECH/TRANSPORT",
  "cage": "🪞",
  "ch": 1,
  "room": "욕망",
  "loop": "L",
  "held": "UberCab이냐 Pad Pass냐 — 두 아이디어뿐",
  "src": "bocconi"
 },
 {
  "name": "Red Bull",
  "year": "1982",
  "country": "🌐",
  "unit": "",
  "outcome": "BEVERAGE",
  "cage": "🪞",
  "ch": 1,
  "room": "욕망",
  "loop": "L",
  "held": "창업이냐 회사에 남느냐",
  "src": "bocconi"
 },
 {
  "name": "Geox",
  "year": "1991",
  "country": "🌐",
  "unit": "",
  "outcome": "FOOTWEAR",
  "cage": "🪞",
  "ch": 1,
  "room": "욕망",
  "loop": "L",
  "held": "가업 와인이냐 통기성 신발이냐",
  "src": "bocconi"
 },
 {
  "name": "ByteDance",
  "year": "2012",
  "country": "🌐",
  "unit": "",
  "outcome": "TECH",
  "cage": "🪞",
  "ch": 1,
  "room": "욕망",
  "loop": "L",
  "held": "99Fang을 키우냐 추천엔진을 새로 하냐",
  "src": "bocconi"
 },
 {
  "name": "Bumble",
  "year": "2014",
  "country": "🌐",
  "unit": "",
  "outcome": "TECH",
  "cage": "🪞",
  "ch": 1,
  "room": "욕망",
  "loop": "L",
  "held": "떠난 자리에서 무엇을 세우냐",
  "src": "bocconi"
 },
 {
  "name": "Pinduoduo",
  "year": "2015",
  "country": "🌐",
  "unit": "",
  "outcome": "E-COMMERCE",
  "cage": "🪞",
  "ch": 1,
  "room": "욕망",
  "loop": "L",
  "held": "소셜 커머스라는 새 형태를 거느냐",
  "src": "bocconi"
 },
 {
  "name": "Grammarly",
  "year": "2009",
  "country": "🌐",
  "unit": "",
  "outcome": "TECH",
  "cage": "🪞",
  "ch": 1,
  "room": "욕망",
  "loop": "L",
  "held": "잘 되는 표절검사냐 AI 글쓰기냐",
  "src": "bocconi"
 },
 {
  "name": "Canva",
  "year": "2013",
  "country": "🌐",
  "unit": "",
  "outcome": "TECH",
  "cage": "🪞",
  "ch": 1,
  "room": "욕망",
  "loop": "L",
  "held": "남이 어려워하는 것을 보고 무엇을 지을까",
  "src": "bocconi"
 },
 {
  "name": "Cirque du Soleil",
  "year": "1984",
  "country": "🌐",
  "unit": "",
  "outcome": "ENTERTAINMENT",
  "cage": "🪞",
  "ch": 1,
  "room": "욕망",
  "loop": "L",
  "held": "거리 공연자가 새 서커스를 세울까",
  "src": "bocconi"
 },
 {
  "name": "Eataly",
  "year": "2004",
  "country": "🌐",
  "unit": "",
  "outcome": "FOOD & BEVERAGE",
  "cage": "🪞",
  "ch": 1,
  "room": "욕망",
  "loop": "L",
  "held": "새 개념이냐 표준 소매냐",
  "src": "bocconi"
 },
 {
  "name": "Booking.com",
  "year": "1996",
  "country": "🌐",
  "unit": "",
  "outcome": "TECH",
  "cage": "🪞",
  "ch": 1,
  "room": "욕망",
  "loop": "L",
  "held": "마케팅 공간이냐 다른 자리냐",
  "src": "bocconi"
 },
 {
  "name": "Revolut",
  "year": "2015",
  "country": "🌐",
  "unit": "",
  "outcome": "FINTECH",
  "cage": "🪞",
  "ch": 1,
  "room": "욕망",
  "loop": "L",
  "held": "핀테크를 어디서 시작하냐",
  "src": "bocconi"
 },
 {
  "name": "Farfetch",
  "year": "2008",
  "country": "🌐",
  "unit": "",
  "outcome": "FASHION E-COM",
  "cage": "🪞",
  "ch": 1,
  "room": "욕망",
  "loop": "L",
  "held": "이커머스로 가냐 오프라인에 남냐",
  "src": "bocconi"
 },
 {
  "name": "Spotify",
  "year": "2008",
  "country": "🌐",
  "unit": "",
  "outcome": "TECH",
  "cage": "🪞",
  "ch": 1,
  "room": "욕망",
  "loop": "L",
  "held": "음악 산업의 교착을 어느 쪽에서 푸냐",
  "src": "bocconi"
 },
 {
  "name": "Nokia",
  "year": "2011",
  "country": "🌐",
  "unit": "",
  "outcome": "TECH",
  "cage": "🔭",
  "ch": 2,
  "room": "상상",
  "loop": "L",
  "held": "세계 1위의 자리와 자기 운영체제",
  "src": "bocconi"
 },
 {
  "name": "Eastman Kodak",
  "year": "1993",
  "country": "🌐",
  "unit": "",
  "outcome": "PHOTOGRAPHY",
  "cage": "🔭",
  "ch": 2,
  "room": "상상",
  "loop": "L",
  "held": "필름의 지배력과 디지털 특허를 동시에",
  "src": "bocconi"
 },
 {
  "name": "IBM",
  "year": "1993",
  "country": "🌐",
  "unit": "",
  "outcome": "TECH",
  "cage": "🔭",
  "ch": 2,
  "room": "상상",
  "loop": "L",
  "held": "메인프레임의 권위",
  "src": "bocconi"
 },
 {
  "name": "Sony",
  "year": "1994",
  "country": "🌐",
  "unit": "",
  "outcome": "TECH",
  "cage": "🔭",
  "ch": 2,
  "room": "상상",
  "loop": "L",
  "held": "가전의 평판, 그리고 결별한 협력자",
  "src": "bocconi"
 },
 {
  "name": "Porsche",
  "year": "1992",
  "country": "🌐",
  "unit": "",
  "outcome": "AUTOMOTIVE",
  "cage": "🔭",
  "ch": 2,
  "room": "상상",
  "loop": "L",
  "held": "장인의 이름과 깊어진 적자",
  "src": "bocconi"
 },
 {
  "name": "Royal Dutch Shell",
  "year": "2004",
  "country": "🌐",
  "unit": "",
  "outcome": "ENERGY",
  "cage": "🔭",
  "ch": 2,
  "room": "상상",
  "loop": "L",
  "held": "매장량 스캔들 뒤의 신뢰",
  "src": "bocconi"
 },
 {
  "name": "BP",
  "year": "2005",
  "country": "🌐",
  "unit": "",
  "outcome": "ENERGY",
  "cage": "🔭",
  "ch": 2,
  "room": "상상",
  "loop": "L",
  "held": "석유 거인의 자리",
  "src": "bocconi"
 },
 {
  "name": "Boeing",
  "year": "2019",
  "country": "🌐",
  "unit": "",
  "outcome": "AEROSPACE",
  "cage": "🔭",
  "ch": 2,
  "room": "상상",
  "loop": "L",
  "held": "안전의 평판",
  "src": "bocconi"
 },
 {
  "name": "HP",
  "year": "2014",
  "country": "🌐",
  "unit": "",
  "outcome": "TECH",
  "cage": "🔭",
  "ch": 2,
  "room": "상상",
  "loop": "L",
  "held": "한 회사라는 형태",
  "src": "bocconi"
 },
 {
  "name": "Toyota",
  "year": "2021",
  "country": "🌐",
  "unit": "",
  "outcome": "AUTOMOTIVE",
  "cage": "🔭",
  "ch": 2,
  "room": "상상",
  "loop": "L",
  "held": "생산방식의 모범이라는 지위",
  "src": "bocconi"
 },
 {
  "name": "Tesla",
  "year": "2008",
  "country": "🌐",
  "unit": "",
  "outcome": "AUTOMOTIVE",
  "cage": "💒",
  "ch": 3,
  "room": "설득",
  "loop": "L",
  "held": "업계 관행을 거스르는 하나의 믿음",
  "src": "bocconi"
 },
 {
  "name": "OpenAI",
  "year": "2019",
  "country": "🌐",
  "unit": "",
  "outcome": "TECH",
  "cage": "💒",
  "ch": 3,
  "room": "설득",
  "loop": "L",
  "held": "한 방향의 확장에 거는 자원",
  "src": "bocconi"
 },
 {
  "name": "NVIDIA",
  "year": "2012",
  "country": "🌐",
  "unit": "",
  "outcome": "TECH",
  "cage": "💒",
  "ch": 3,
  "room": "설득",
  "loop": "L",
  "held": "게임용 칩을 다른 용도에 거는 판단",
  "src": "bocconi"
 },
 {
  "name": "Pfizer",
  "year": "2020",
  "country": "🌐",
  "unit": "",
  "outcome": "PHARMA",
  "cage": "💒",
  "ch": 3,
  "room": "설득",
  "loop": "L",
  "held": "백신 한 경로에 거는 속도",
  "src": "bocconi"
 },
 {
  "name": "Novo Nordisk",
  "year": "2021",
  "country": "🌐",
  "unit": "",
  "outcome": "HEALTHCARE",
  "cage": "💒",
  "ch": 3,
  "room": "설득",
  "loop": "L",
  "held": "한 적응증에 거는 집중",
  "src": "bocconi"
 },
 {
  "name": "UBS",
  "year": "2023",
  "country": "🌐",
  "unit": "",
  "outcome": "FINANCE",
  "cage": "💒",
  "ch": 3,
  "room": "설득",
  "loop": "L",
  "held": "크레디트스위스 인수라는 큰 베팅",
  "src": "bocconi"
 },
 {
  "name": "Google and YouTube",
  "year": "2006",
  "country": "🌐",
  "unit": "",
  "outcome": "TECH",
  "cage": "💒",
  "ch": 3,
  "room": "설득",
  "loop": "L",
  "held": "내부 개발이냐 인수냐",
  "src": "bocconi"
 },
 {
  "name": "Disney-Pixar",
  "year": "2005",
  "country": "🌐",
  "unit": "",
  "outcome": "ENTERTAINMENT",
  "cage": "💒",
  "ch": 3,
  "room": "설득",
  "loop": "L",
  "held": "인수에 거는 애니메이션의 미래",
  "src": "bocconi"
 },
 {
  "name": "EssilorLuxottica",
  "year": "2018",
  "country": "🌐",
  "unit": "",
  "outcome": "EYEWEAR",
  "cage": "💒",
  "ch": 3,
  "room": "설득",
  "loop": "L",
  "held": "합병이냐 각자 전문가로 남느냐",
  "src": "bocconi"
 },
 {
  "name": "Carlyle",
  "year": "2013",
  "country": "🌐",
  "unit": "",
  "outcome": "PRIVATE EQUITY",
  "cage": "💒",
  "ch": 3,
  "room": "설득",
  "loop": "L",
  "held": "IPO냐 매각이냐",
  "src": "bocconi"
 },
 {
  "name": "eBay & PayPal",
  "year": "2014",
  "country": "🌐",
  "unit": "",
  "outcome": "E-COMMERCE",
  "cage": "💒",
  "ch": 3,
  "room": "설득",
  "loop": "L",
  "held": "분리하라는 압박 앞에서",
  "src": "bocconi"
 },
 {
  "name": "Epic Games",
  "year": "2019",
  "country": "🌐",
  "unit": "",
  "outcome": "TECH",
  "cage": "💒",
  "ch": 3,
  "room": "설득",
  "loop": "L",
  "held": "방향 하나에 거는 전환",
  "src": "bocconi"
 },
 {
  "name": "Nintendo",
  "year": "1972",
  "country": "🌐",
  "unit": "",
  "outcome": "GAMING",
  "cage": "⏱️",
  "ch": 4,
  "room": "폭파",
  "loop": "L",
  "held": "화투에서 쌓은 체제",
  "src": "bocconi"
 },
 {
  "name": "Microsoft",
  "year": "1995",
  "country": "🌐",
  "unit": "",
  "outcome": "TECH",
  "cage": "⏱️",
  "ch": 4,
  "room": "폭파",
  "loop": "L",
  "held": "윈도라는 돌아가는 질서",
  "src": "bocconi"
 },
 {
  "name": "Marvel",
  "year": "1996",
  "country": "🌐",
  "unit": "",
  "outcome": "ENTERTAINMENT",
  "cage": "⏱️",
  "ch": 4,
  "room": "폭파",
  "loop": "L",
  "held": "출판으로 굳은 형식",
  "src": "bocconi"
 },
 {
  "name": "Lego",
  "year": "2003",
  "country": "🌐",
  "unit": "",
  "outcome": "TOYS",
  "cage": "⏱️",
  "ch": 4,
  "room": "폭파",
  "loop": "L",
  "held": "브릭이라는 지배적 설계",
  "src": "bocconi"
 },
 {
  "name": "Netflix",
  "year": "2011",
  "country": "🌐",
  "unit": "",
  "outcome": "TECH/MEDIA",
  "cage": "⏱️",
  "ch": 4,
  "room": "폭파",
  "loop": "L",
  "held": "DVD 우편이라는 성공한 공정",
  "src": "bocconi"
 },
 {
  "name": "Intel Centrino",
  "year": "2003",
  "country": "🌐",
  "unit": "",
  "outcome": "TECH",
  "cage": "⏱️",
  "ch": 4,
  "room": "폭파",
  "loop": "L",
  "held": "속도 경쟁이라는 굳은 규칙",
  "src": "bocconi"
 },
 {
  "name": "IKEA India",
  "year": "2018",
  "country": "🌐",
  "unit": "",
  "outcome": "RETAIL",
  "cage": "⏱️",
  "ch": 4,
  "room": "폭파",
  "loop": "L",
  "held": "전 세계에서 통한 한 매장 공식",
  "src": "bocconi"
 },
 {
  "name": "WeChat (Tencent)",
  "year": "2011",
  "country": "🌐",
  "unit": "",
  "outcome": "TECH",
  "cage": "⏱️",
  "ch": 4,
  "room": "폭파",
  "loop": "L",
  "held": "QQ라는 이미 도는 체제",
  "src": "bocconi"
 },
 {
  "name": "Klarna",
  "year": "2005",
  "country": "🌐",
  "unit": "",
  "outcome": "FINTECH",
  "cage": "⏱️",
  "ch": 4,
  "room": "폭파",
  "loop": "L",
  "held": "결제라는 굳은 순서",
  "src": "bocconi"
 },
 {
  "name": "Pagani Automobili",
  "year": "1999",
  "country": "🌐",
  "unit": "",
  "outcome": "AUTOMOTIVE",
  "cage": "⏱️",
  "ch": 4,
  "room": "폭파",
  "loop": "L",
  "held": "수작업이라는 질서",
  "src": "bocconi"
 },
 {
  "name": "Calm",
  "year": "2016",
  "country": "🌐",
  "unit": "",
  "outcome": "TECH",
  "cage": "⏱️",
  "ch": 4,
  "room": "폭파",
  "loop": "L",
  "held": "성장하던 방식",
  "src": "bocconi"
 }
];
