// 생성물 — .claude/gen_startup_cases.py 가 만든다. 손으로 고치지 말 것.
// 고칠 곳: 시공간멜로디/On/me_문현지/제품/전집/company/<회사>.md 의 frontmatter
const CASES = [
 {
  "name": "달바 (d'Alba)",
  "country": "🇰🇷",
  "cage": "🪞",
  "ch": 1,
  "unit": "bit",
  "founded": "2018",
  "outcome": "성장 중",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "무신사 (Musinsa)",
  "country": "🇰🇷",
  "cage": "🪞",
  "ch": 1,
  "unit": "bit",
  "founded": "2001",
  "outcome": "성장 중",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "야놀자 (Yanolja)",
  "country": "🇰🇷",
  "cage": "🪞",
  "ch": 1,
  "unit": "bit",
  "founded": "2005",
  "outcome": "성장 중",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "컬리 (Kurly)",
  "country": "🇰🇷",
  "cage": "🪞",
  "ch": 1,
  "unit": "bit",
  "founded": "2015",
  "outcome": "성장 중",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "Juicero",
  "country": "🇺🇸",
  "cage": "🪞",
  "ch": 1,
  "unit": "atom",
  "founded": "2013",
  "outcome": "실패",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "Lytro",
  "country": "🇺🇸",
  "cage": "🪞",
  "ch": 1,
  "unit": "atom",
  "founded": "2006",
  "outcome": "실패",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "Magic Leap",
  "country": "🇺🇸",
  "cage": "🪞",
  "ch": 1,
  "unit": "atom",
  "founded": "2010",
  "outcome": "피봇",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "Quibi",
  "country": "🇺🇸",
  "cage": "🪞",
  "ch": 1,
  "unit": "bit",
  "founded": "2018",
  "outcome": "실패",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "Honda",
  "country": "🇯🇵",
  "cage": "🔭",
  "ch": 2,
  "unit": "atom",
  "founded": "1948",
  "outcome": "성공",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "HD현대 (HD Hyundai)",
  "country": "🇰🇷",
  "cage": "🔭",
  "ch": 2,
  "unit": "atom",
  "founded": "1972",
  "outcome": "성공",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "LS일렉트릭 (LS Electric)",
  "country": "🇰🇷",
  "cage": "🔭",
  "ch": 2,
  "unit": "second",
  "founded": "1974",
  "outcome": "성공",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "리피드 (Lipid)",
  "country": "🇰🇷",
  "cage": "🔭",
  "ch": 2,
  "unit": "atom",
  "founded": "2020",
  "outcome": "초기 성장",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "한화에어로스페이스 (Hanwha Aerospace)",
  "country": "🇰🇷",
  "cage": "🔭",
  "ch": 2,
  "unit": "atom",
  "founded": "1977",
  "outcome": "성공",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "한화오션 (Hanwha Ocean)",
  "country": "🇰🇷",
  "cage": "🔭",
  "ch": 2,
  "unit": "atom",
  "founded": "1973",
  "outcome": "성공",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "Airbnb",
  "country": "🇺🇸",
  "cage": "🔭",
  "ch": 2,
  "unit": "bit",
  "founded": "2008",
  "outcome": "성공",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "Kodak",
  "country": "🇺🇸",
  "cage": "🔭",
  "ch": 2,
  "unit": "bit",
  "founded": "1892",
  "outcome": "실패(파산)",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "SK바이오팜 (SK Biopharmaceuticals)",
  "country": "🇰🇷",
  "cage": "💒",
  "ch": 3,
  "unit": "cell",
  "founded": "1993",
  "outcome": "성공",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "삼성바이오로직스 (Samsung Biologics)",
  "country": "🇰🇷",
  "cage": "💒",
  "ch": 3,
  "unit": "cell",
  "founded": "2011",
  "outcome": "성공",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "셀트리온 (Celltrion)",
  "country": "🇰🇷",
  "cage": "💒",
  "ch": 3,
  "unit": "cell",
  "founded": "2002",
  "outcome": "성공",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "알테오젠 (Alteogen)",
  "country": "🇰🇷",
  "cage": "💒",
  "ch": 3,
  "unit": "cell",
  "founded": "2008",
  "outcome": "성장 중",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "에이비엘바이오 (ABL Bio)",
  "country": "🇰🇷",
  "cage": "💒",
  "ch": 3,
  "unit": "cell",
  "founded": "2016",
  "outcome": "성장 중",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "Flagship Pioneering",
  "country": "🇺🇸",
  "cage": "💒",
  "ch": 3,
  "unit": "cell",
  "founded": "2000",
  "outcome": "성공",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "Intel",
  "country": "🇺🇸",
  "cage": "💒",
  "ch": 3,
  "unit": "atom",
  "founded": "1968",
  "outcome": "위기 중",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "Moderna",
  "country": "🇺🇸",
  "cage": "💒",
  "ch": 3,
  "unit": "cell",
  "founded": "2010",
  "outcome": "성공",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "Theranos",
  "country": "🇺🇸",
  "cage": "💒",
  "ch": 3,
  "unit": "cell",
  "founded": "2003",
  "outcome": "실패",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "Ferrari",
  "country": "🇮🇹",
  "cage": "⏱️",
  "ch": 4,
  "unit": "atom",
  "founded": "1947",
  "outcome": "성공",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "두산",
  "country": "🇰🇷",
  "cage": "⏱️",
  "ch": 4,
  "unit": "second",
  "founded": "1896",
  "outcome": "성공",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "뤼튼 (Wrtn)",
  "country": "🇰🇷",
  "cage": "⏱️",
  "ch": 4,
  "unit": "bit",
  "founded": "2021",
  "outcome": "성장 중",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "쿠팡 (Coupang)",
  "country": "🇰🇷",
  "cage": "⏱️",
  "ch": 4,
  "unit": "bit",
  "founded": "2010",
  "outcome": "성장 중",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "크래프톤 (Krafton)",
  "country": "🇰🇷",
  "cage": "⏱️",
  "ch": 4,
  "unit": "bit",
  "founded": "2007",
  "outcome": "성공",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "LeEco",
  "country": "🇨🇳",
  "cage": "🦋",
  "ch": 6,
  "unit": "bit",
  "founded": "2004",
  "outcome": "실패(과확장·자금경색)",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "텐센트 (Tencent)",
  "country": "🇨🇳",
  "cage": "🦋",
  "ch": 6,
  "unit": "bit",
  "founded": "1998",
  "outcome": "성공",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "닌텐도 (Nintendo)",
  "country": "🇯🇵",
  "cage": "🦋",
  "ch": 6,
  "unit": "bit",
  "founded": "1889",
  "outcome": "성공",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "라인 (LINE)",
  "country": "🇯🇵",
  "cage": "🦋",
  "ch": 6,
  "unit": "bit",
  "founded": "2011",
  "outcome": "성공",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "Faraday Future",
  "country": "🇺🇸",
  "cage": "🦋",
  "ch": 6,
  "unit": "atom",
  "founded": "2014",
  "outcome": "실패",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "Novo Nordisk",
  "country": "🇩🇰",
  "cage": "🌷",
  "ch": 7,
  "unit": "cell",
  "founded": "1923",
  "outcome": "성공",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "Better Place",
  "country": "🇮🇱",
  "cage": "🌷",
  "ch": 7,
  "unit": "second",
  "founded": "2007",
  "outcome": "실패",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "Netafim",
  "country": "🇮🇱",
  "cage": "🌷",
  "ch": 7,
  "unit": "atom",
  "founded": "1965",
  "outcome": "성공",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "ASML",
  "country": "🇳🇱",
  "cage": "🌷",
  "ch": 7,
  "unit": "atom",
  "founded": "1984",
  "outcome": "성공",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "Aduhelm (Biogen)",
  "country": "🇺🇸",
  "cage": "🌷",
  "ch": 7,
  "unit": "cell",
  "founded": "2021",
  "outcome": "실패(승인 논란)",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "Tesla",
  "country": "🇺🇸",
  "cage": "🌷",
  "ch": 7,
  "unit": "atom",
  "founded": "2003",
  "outcome": "성공",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "MercadoLibre",
  "country": "🇦🇷",
  "cage": "🌫️",
  "ch": 8,
  "unit": "bit",
  "founded": "1999",
  "outcome": "성공",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "Nubank",
  "country": "🇧🇷",
  "cage": "🌫️",
  "ch": 8,
  "unit": "bit",
  "founded": "2013",
  "outcome": "성공",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "Gowex",
  "country": "🇪🇸",
  "cage": "🌫️",
  "ch": 8,
  "unit": "bit",
  "founded": "",
  "outcome": "실패(분식회계)",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "Beyond Meat",
  "country": "🇺🇸",
  "cage": "🌫️",
  "ch": 8,
  "unit": "cell",
  "founded": "2009",
  "outcome": "실패(붕괴)",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "Impossible Foods",
  "country": "🇺🇸",
  "cage": "🌫️",
  "ch": 8,
  "unit": "cell",
  "founded": "2011",
  "outcome": "성공",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "Pivot Bio",
  "country": "🇺🇸",
  "cage": "🌫️",
  "ch": 8,
  "unit": "cell",
  "founded": "2011",
  "outcome": "성공",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "배달의민족",
  "country": "🇰🇷",
  "cage": "🐦‍⬛",
  "ch": 9,
  "unit": "bit",
  "founded": "2010",
  "outcome": "인수(성공)",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "카카오 (Kakao)",
  "country": "🇰🇷",
  "cage": "🐦‍⬛",
  "ch": 9,
  "unit": "bit",
  "founded": "2010",
  "outcome": "위기 중",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "토스 (Toss/Viva Republica)",
  "country": "🇰🇷",
  "cage": "🐦‍⬛",
  "ch": 9,
  "unit": "bit",
  "founded": "2013",
  "outcome": "성장 중",
  "borrowed": "",
  "lost": ""
 },
 {
  "name": "Groq",
  "country": "🇺🇸",
  "cage": "🐦‍⬛",
  "ch": 9,
  "unit": "atom",
  "founded": "2016",
  "outcome": "성공",
  "borrowed": "",
  "lost": ""
 }
];
